// Shibuli digital electronics - Static product data
// Prices are in Kenyan Shillings (KES). Images use Unsplash URLs with an
// automatic SVG fallback (handled in store.js) so the site works offline too.

const CATEGORIES = [
  { id: "smartphones", name: "Smartphones", icon: "📱" },
  { id: "laptops", name: "Laptops", icon: "💻" },
  { id: "tvs", name: "TVs", icon: "📺" },
  { id: "audio", name: "Audio", icon: "🎧" },
  { id: "accessories", name: "Accessories", icon: "🔌" },
  { id: "gaming", name: "Gaming", icon: "🎮" },
];

const PRODUCTS = [
  {
    id: "samsung-galaxy-s25",
    name: "Samsung Galaxy S25",
    category: "smartphones",
    price: 115000,
    oldPrice: 125000,
    rating: 4.8,
    reviews: 214,
    badge: "New",
    stock: 23,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=60",
    short: "Flagship 6.2\" AMOLED smartphone with AI camera and all-day battery.",
    description:
      "The Samsung Galaxy S25 delivers pro-grade photography, a brilliant 120Hz AMOLED display and an intelligent processor built for speed. Designed to keep up with your busiest days.",
    specs: {
      Display: "6.2-inch Dynamic AMOLED 120Hz",
      Processor: "Snapdragon 8 Elite",
      RAM: "12GB",
      Storage: "256GB",
      Battery: "4000mAh",
      Camera: "50MP + 12MP + 10MP",
    },
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    category: "smartphones",
    price: 135000,
    oldPrice: 145000,
    rating: 4.9,
    reviews: 389,
    badge: "-7%",
    stock: 17,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=600&q=60",
    short: "A18 chip, Camera Control and a tough yet beautiful design.",
    description:
      "iPhone 16 features the powerful A18 chip, a 48MP Fusion camera system and the new Camera Control for instant shooting. Built with aerospace-grade aluminium.",
    specs: {
      Display: "6.1-inch Super Retina XDR",
      Processor: "A18 Bionic",
      RAM: "8GB",
      Storage: "256GB",
      Battery: "Up to 22h video",
      Camera: "48MP + 12MP",
    },
  },
  {
    id: "tecno-camon-30",
    name: "Tecno Camon 30",
    category: "smartphones",
    price: 28000,
    rating: 4.5,
    reviews: 156,
    badge: "Hot",
    stock: 41,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=60",
    short: "Stunning 108MP camera and smooth 120Hz display at a great price.",
    description:
      "Capture every moment in vivid detail with the 108MP Ultra Night Camera. A 120Hz display and long-lasting battery make the Camon 30 perfect for everyday life.",
    specs: {
      Display: "6.78-inch AMOLED 120Hz",
      Processor: "Helio G99 Ultimate",
      RAM: "8GB",
      Storage: "256GB",
      Battery: "5000mAh",
      Camera: "108MP + 2MP",
    },
  },
  {
    id: "hp-elitebook-840",
    name: "HP EliteBook 840 G11",
    category: "laptops",
    price: 95000,
    oldPrice: 105000,
    rating: 4.6,
    reviews: 98,
    badge: "-10%",
    stock: 12,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=60",
    short: "Business laptop with 14\" display and all-day productivity.",
    description:
      "The HP EliteBook 840 is built for professionals who need security, performance and portability. A crisp 14-inch display and enterprise-grade features keep you productive anywhere.",
    specs: {
      Display: "14-inch FHD IPS",
      Processor: "Intel Core Ultra 7",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "51Wh",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "laptops",
    price: 145000,
    rating: 4.7,
    reviews: 121,
    badge: "Premium",
    stock: 9,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=60",
    short: "Ultra-light carbon-fibre laptop with legendary keyboard.",
    description:
      "The ThinkPad X1 Carbon combines a feather-light carbon-fibre chassis with a brilliant display and the legendary ThinkPad keyboard. Engineered for executives on the move.",
    specs: {
      Display: "14-inch 2.8K OLED",
      Processor: "Intel Core Ultra 7",
      RAM: "32GB",
      Storage: "1TB SSD",
      Battery: "57Wh",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "dell-latitude-7440",
    name: "Dell Latitude 7440",
    category: "laptops",
    price: 110000,
    rating: 4.5,
    reviews: 74,
    badge: "New",
    stock: 15,
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=60",
    short: "Reliable 14\" business laptop with modern connectivity.",
    description:
      "Dell Latitude 7440 offers dependable performance, enhanced privacy features and a comfortable, modern design for today's hybrid workplace.",
    specs: {
      Display: "14-inch FHD",
      Processor: "Intel Core i7",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "54Wh",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "samsung-55-tv",
    name: 'Samsung 55" Smart TV',
    category: "tvs",
    price: 85000,
    oldPrice: 95000,
    rating: 4.7,
    reviews: 142,
    badge: "-11%",
    stock: 20,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=60",
    short: 'Crystal UHD 55" 4K Smart TV with vibrant colour.',
    description:
      'Experience cinematic 4K picture quality with the Samsung 55" Crystal UHD Smart TV. Stream your favourites and control everything with your voice.',
    specs: {
      Display: '55-inch 4K UHD',
      Resolution: "3840 x 2160",
      Smart: "Tizen OS",
      HDR: "HDR10+",
      Connectivity: "HDMI x3, USB x2, Wi-Fi",
      Sound: "20W Dolby Digital Plus",
    },
  },
  {
    id: "lg-50-tv",
    name: 'LG 50" Smart TV',
    category: "tvs",
    price: 65000,
    rating: 4.6,
    reviews: 88,
    badge: "Value",
    stock: 26,
    image: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=600&q=60",
    short: '50" 4K AI ThinQ Smart TV with webOS.',
    description:
      'The LG 50" 4K Smart TV brings vivid colours and smart features powered by webOS and the α5 AI processor for an upgraded viewing experience.',
    specs: {
      Display: '50-inch 4K UHD',
      Resolution: "3840 x 2160",
      Smart: "webOS 24",
      HDR: "HDR10 / HLG",
      Connectivity: "HDMI x3, USB x2, Wi-Fi",
      Sound: "20W AI Sound",
    },
  },
  {
    id: "jbl-speaker",
    name: "JBL Bluetooth Speaker",
    category: "audio",
    price: 12500,
    rating: 4.5,
    reviews: 203,
    badge: "Hot",
    stock: 60,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=60",
    short: "Portable waterproof speaker with deep bass.",
    description:
      "Take your music anywhere with the JBL portable Bluetooth speaker. Waterproof, durable and packing surprisingly powerful bass for its size.",
    specs: {
      Connectivity: "Bluetooth 5.3",
      Battery: "Up to 12 hours",
      Waterproof: "IPX7",
      Power: "20W",
      Weight: "540g",
      Colour: "Black",
    },
  },
  {
    id: "sony-headphones",
    name: "Sony WH-1000XM5 Headphones",
    category: "audio",
    price: 32000,
    oldPrice: 38000,
    rating: 4.8,
    reviews: 312,
    badge: "-16%",
    stock: 33,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=60",
    short: "Industry-leading noise cancelling over-ear headphones.",
    description:
      "Immerse yourself in sound with the Sony WH-1000XM5. Industry-leading noise cancellation, crystal-clear calls and up to 30 hours of battery life.",
    specs: {
      Type: "Over-ear wireless",
      ANC: "Yes (best-in-class)",
      Battery: "30 hours",
      Connectivity: "Bluetooth 5.2",
      Weight: "250g",
      Mic: "8-mic array",
    },
  },
  {
    id: "apple-airpods",
    name: "Apple AirPods Pro 2",
    category: "audio",
    price: 28000,
    rating: 4.9,
    reviews: 421,
    badge: "Best Seller",
    stock: 45,
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=600&q=60",
    short: "Active noise cancellation with adaptive audio.",
    description:
      "AirPods Pro 2 feature active noise cancellation, Adaptive Audio and a customisable fit for all-day comfort. Magical, effortless and immersive.",
    specs: {
      Type: "In-ear wireless",
      ANC: "Active Noise Cancellation",
      Battery: "6h + 30h case",
      Connectivity: "Bluetooth 5.3",
      Chip: "H2",
      Charging: "USB-C / MagSafe",
    },
  },
  {
    id: "smart-watch-pro",
    name: "Smart Watch Pro",
    category: "accessories",
    price: 9500,
    rating: 4.3,
    reviews: 167,
    badge: "New",
    stock: 52,
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=60",
    short: "Health & fitness smartwatch with AMOLED display.",
    description:
      "Track your heart rate, sleep and workouts with the Smart Watch Pro. A vivid AMOLED display and 7-day battery keep you connected and healthy.",
    specs: {
      Display: "1.96-inch AMOLED",
      Battery: "Up to 7 days",
      Sensors: "Heart rate, SpO2, Sleep",
      Waterproof: "IP68",
      Compatibility: "Android / iOS",
      Connectivity: "Bluetooth 5.2",
    },
  },
  {
    id: "gaming-mouse",
    name: "Gaming Mouse RGB",
    category: "gaming",
    price: 4500,
    rating: 4.4,
    reviews: 189,
    badge: "Hot",
    stock: 70,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=60",
    short: "High-precision 16000 DPI gaming mouse with RGB.",
    description:
      "Dominate the game with a lightweight 16000 DPI gaming mouse. Customisable RGB lighting and ultra-fast response for competitive play.",
    specs: {
      DPI: "16000",
      Buttons: "6 programmable",
      Polling: "1000Hz",
      Lighting: "RGB",
      Connection: "USB wired",
      Weight: "75g",
    },
  },
  {
    id: "mechanical-keyboard",
    name: "Mechanical Keyboard",
    category: "accessories",
    price: 8000,
    oldPrice: 9500,
    rating: 4.6,
    reviews: 134,
    badge: "-16%",
    stock: 38,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=60",
    short: "Hot-swappable mechanical keyboard with RGB.",
    description:
      "Type and game with satisfying precision on this hot-swappable mechanical keyboard. RGB backlighting and a sturdy aluminium frame complete the build.",
    specs: {
      Switches: "Hot-swappable Red",
      Layout: "TKL 87-key",
      Lighting: "RGB",
      Connection: "USB-C / Bluetooth",
      Build: "Aluminium",
      Compatibility: "Windows / Mac",
    },
  },
  {
    id: "flash-drive-128",
    name: "128GB Flash Drive",
    category: "accessories",
    price: 1500,
    rating: 4.2,
    reviews: 256,
    badge: "Value",
    stock: 120,
    image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?auto=format&fit=crop&w=600&q=60",
    short: "Compact 128GB USB 3.2 flash drive for fast transfer.",
    description:
      "Carry your files anywhere with this compact 128GB USB 3.2 flash drive. Fast transfer speeds and a durable metal casing.",
    specs: {
      Capacity: "128GB",
      Interface: "USB 3.2 Gen 1",
      Read: "Up to 150MB/s",
      Build: "Metal",
      Warranty: "5 years",
      OS: "All",
    },
  },
  {
    id: "playstation-5",
    name: "PlayStation 5 Console",
    category: "gaming",
    price: 75000,
    rating: 4.9,
    reviews: 278,
    badge: "Best Seller",
    stock: 14,
    image: "https://images.unsplash.com/photo-1606141401011-6e9a1830c9b9?auto=format&fit=crop&w=600&q=60",
    short: "Next-gen gaming with lightning-fast SSD.",
    description:
      "Experience lightning-fast loading, 3D audio and stunning 4K visuals with the PlayStation 5. The future of gaming is here.",
    specs: {
      CPU: "AMD Zen 2 8-core",
      GPU: "AMD RDNA 2 10.3 TFLOPS",
      Storage: "825GB SSD",
      Output: "4K 120fps",
      Audio: "Tempest 3D",
      Includes: "DualSense controller",
    },
  },
  {
    id: "xbox-controller",
    name: "Xbox Wireless Controller",
    category: "gaming",
    price: 9000,
    rating: 4.5,
    reviews: 145,
    badge: "New",
    stock: 48,
    image: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=600&q=60",
    short: "Precision controller with Bluetooth for Xbox & PC.",
    description:
      "Play across Xbox, PC and mobile with the Xbox Wireless Controller. Textured grip, refined buttons and Bluetooth connectivity.",
    specs: {
      Connection: "Bluetooth / Xbox Wireless",
      Compatibility: "Xbox, PC, Mobile",
      Battery: "AA / rechargeable",
      Features: "Textured grip, Share button",
      Colour: "Carbon Black",
    },
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    category: "laptops",
    price: 165000,
    rating: 4.9,
    reviews: 167,
    badge: "Premium",
    stock: 8,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=60",
    short: "Feather-light laptop with the blazing M3 chip.",
    description:
      "The MacBook Air with the M3 chip delivers exceptional speed and up to 18 hours of battery in a silent, fanless design. Perfectly portable power.",
    specs: {
      Display: "13.6-inch Liquid Retina",
      Processor: "Apple M3",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "Up to 18 hours",
      OS: "macOS",
    },
  },
];

// Allow reuse from other scripts
window.TECHHUB = window.TECHHUB || {};
window.TECHHUB.CATEGORIES = CATEGORIES;
window.TECHHUB.PRODUCTS = PRODUCTS;
